// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3kiv2QVJIuwE7nxghZAPWcVmd77-3HWU',
    appId: '1:229672874986:web:5a37ec0c940a9747bdb893',
    messagingSenderId: '229672874986',
    projectId: 'loginpage-9c51e',
    authDomain: 'loginpage-9c51e.firebaseapp.com',
    storageBucket: 'loginpage-9c51e.appspot.com',
    measurementId: 'G-EF8LLKY4NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD37N62tBYK1CTMs9WItiOKO1oX1b3_cOM',
    appId: '1:229672874986:android:82ef24010a45a204bdb893',
    messagingSenderId: '229672874986',
    projectId: 'loginpage-9c51e',
    storageBucket: 'loginpage-9c51e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK8-J9F-LL5k0OWy_g5t3_5UbDvfqbKMg',
    appId: '1:229672874986:ios:5348c495ca94901dbdb893',
    messagingSenderId: '229672874986',
    projectId: 'loginpage-9c51e',
    storageBucket: 'loginpage-9c51e.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK8-J9F-LL5k0OWy_g5t3_5UbDvfqbKMg',
    appId: '1:229672874986:ios:f368392198c34cd0bdb893',
    messagingSenderId: '229672874986',
    projectId: 'loginpage-9c51e',
    storageBucket: 'loginpage-9c51e.appspot.com',
    iosBundleId: 'com.example.loginpage.RunnerTests',
  );
}
